# Composite private action to setup the CI environment with all the tools needed for the project.
# We could install pre-commit too here
name: Setup CI
description: 'Setup CI environment with all the tools needed for the project'
inputs:
  install_scripts:
    description: 'Whether to install scripts while installing node packages or not'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Install pre-commit
      shell: bash
      run: pipx install pre-commit

    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
        scope: '@gipo355'

    # install dependencies
    - name: Install dependencies
      shell: bash
      run: |
        if [[ "${{ inputs.install_scripts }}" == "true" ]]; then
          pnpm install --frozen-lockfile
        else
          pnpm install --frozen-lockfile --ignore-scripts
        fi
